### PR TITLE
Fix/add proper client side auth api

### PR DESCRIPTION
**Pull request by matboivin**
Hi everyone please fix your part before merging this into `dev`.

Take a look at the documentation here: [Front end authentication flow API](https://github.com/aurelien-brabant/ft_transcendance/wiki/Front-end-authentication-flow-API)

- [x] chat -> mboivin
- [x] relationships -> mboivin
- [x] game -> @Nnevalti 
- [x] hub -> nnevalti
- [x] user profile, leaderboard -> @busshi 
- [x] fix issue on `pages/friends.tsx`

Closes: #72

### CODE REVIEW

**Comment by matboivin** [comment]
I will fix the chat part.

**Comment by aurelien-brabant** [comment]
promoting @matboivin  to product manager

**Comment by matboivin** [comment]
Currently fixing the `relationships` bcs I need it.

**Comment by matboivin** [comment]
Currently fixing an issue on the friends page

**Pull request merged**
