### PR TITLE
[DON'T MERGE - OPEN FOR REVIEWS] API routes protection

### PR DESCRIPTION
**Pull request by aurelien-brabant**
Feel free to review the PR as I'm adding new protections, to make sure that these will not break anything.

### CODE REVIEW

**Review by busshi — COMMENTED** [review]
Sounds OK for me! Gonna make some tests to check if everything is OK...

**Comment by aurelien-brabant** [comment]
> Sounds OK for me! Gonna make some tests to check if everything is OK...

Yeah, that would be nice. I didn't know what to test exactly.

**Review by matboivin — APPROVED** [review]

**Comment by matboivin** [comment]
Maybe the merge should be done into `dev` since it is ahead of `master`?

**Comment by aurelien-brabant** [comment]
#109  supersedes this

**Pull request closed without merging**
