### PR TITLE
add blockedUsers in update-user.dto, and seeders files

### PR DESCRIPTION
**Pull request by AstridDELCROS**

### CODE REVIEW

**Review by aurelien-brabant — CHANGES_REQUESTED** [review]
The following comment applies to that PR as well as the PR #48  #49 (everything related to blocked users)

I don't understand why you created a specific entity for the blocked users. If I'm not mistaken (and I may be) a blocked user is a simple user. There is no additional metadata that needs to be attached to the blocking state, so creating a specific object in database that holds a user in it feels a little bit useless here.

I think the way to go is to simply add a `blockedUsers` field to the already present `User` entity.
A user can by himself have an array of users, every user in that array being a blocked user. There is no need for another entity.

Feel free to discuss this point :)

**Comment by AstridDELCROS** [comment]
I added relations to users.entity and deleted the userBlocked one. But to do so, I had to create blockedUsers **and** user properties in seedUser (seeder). If I didn't add "user" to seedUser, I got `Property 'user' is missing in type 'SeedUser' but required in type 'User'`. What do you think?

**Comment by busshi** [comment]
Yes it is ok. If you change the entity you have to update the seeder too otherwise you have errors like you had because of the DTO

**Comment by AstridDELCROS** [comment]
Well, now it's added because of course I removed just before pushing 😅

**Comment by AstridDELCROS** [comment]
Ok, last commit is useless, I thought I had forgotten user in seeder 🙈

**Review by aurelien-brabant — APPROVED** [review]
Awesome work, thank you for dedication. I think we can merge it when conflicts are resolved.

**Pull request merged**
